Repository Nixtla/hierarchicalforecast, pull requests merged in 2022-12, with the labels that each got.

#121 Factorizing reverse_sigmah from HierarchicalReconciliation
  hierarchicalforecast/_modidx.py
  hierarchicalforecast/core.py
  hierarchicalforecast/utils.py
  nbs/core.ipynb
  nbs/utils.ipynb
Labels: refactor

#134 [FEAT] CRPS, MSSE and Energy Score metrics
  hierarchicalforecast/_modidx.py
  hierarchicalforecast/core.py
  hierarchicalforecast/evaluation.py
  hierarchicalforecast/methods.py
  hierarchicalforecast/probabilistic_methods.py
  nbs/core.ipynb
  nbs/evaluation.ipynb
  nbs/examples/TourismLarge-Evaluation.ipynb
  nbs/methods.ipynb
  nbs/probabilistic_methods.ipynb
Labels: enhancement

#141 [FIX] Circle ci integration
  action_files/test_models/src/data.py
Labels: bug
