Repository Nixtla/hierarchicalforecast, pull requests merged in 2024-07, with the labels that each got.

#272 remove numpy pin
  .github/workflows/ci.yml
  environment.yml
  hierarchicalforecast/utils.py
  nbs/utils.ipynb
  settings.ini
  setup.py
Labels: dependencies

#273 warn when num_threads is not used in MinTrace
  .circleci/config.yml
  hierarchicalforecast/methods.py
  nbs/methods.ipynb
Labels: enhancement

#274 use commit hash in actions and add dependabot updates
  .github/dependabot.yml
  .github/workflows/build-docs.yaml
  .github/workflows/ci.yml
  .github/workflows/no-response.yaml
  .github/workflows/python-publish.yml
  nbs/examples/MLFrameworksExample.ipynb
Labels: dependencies

#264 [FEAT] Efficient MinTrace (ols/wls_var/wls_struct/mint_cov/mint_shrink)
  .gitignore
  hierarchicalforecast/evaluation.py
  hierarchicalforecast/methods.py
  hierarchicalforecast/probabilistic_methods.py
  nbs/core.ipynb
  nbs/methods.ipynb
Labels: feature
